### ISSUE TITLE
can you add feature to parse signal message by openai api like gpt or chatgpt

### ISSUE THREAD

**Issue by ammar0466** [ogunjobiFX/MT4-Forex-Signal-Copier-Telegram-Bot#1]
because sometime signal provider have different formatting, by using ai parsing should be able solve this,

this is kind of response from chatgpt :

```
Yes, I can help you parse these trading signals and generate instructions for automated trading using MetaApi.

Firstly, it is important to note that trading signals should be used with caution, as they may not always be accurate or suitable for your trading strategy. It is important to do your own research and analysis before making any trades.

Now, let's parse the examples you provided:

    USD/JPY signal:

    Symbol: USD/JPY
    Action: Buy
    Entry Price: Current market price (not specified)
    Take Profit: 138.8 pips (1.388 - current market price)
    Stop Loss: 120 pips (1.200 - current market price)

Based on this signal, we can generate the following instructions for MetaApi:
```

**Comment by ammar0466** [comment]
https://www.thedataschool.com.au/daniel-lawson/using-chatgpt-to-parse-unstructured-text/

example case

**Comment by ogunjobiFX** [comment]
This is honestly a great idea. It would be great if other people who use this Telegram bot could add to it. However, I will not be contributing to new features to this open source project myself. If you're interested in me adding it for your own use case, you can reach out to me via ogunjobiforex@gmail.com or https://calendly.com/ogunjobiforex/ogunjobifx-forex-software-consultation to book a consultation. @ammar0466

**Comment by ogunjobiFX** [comment]
Closing this issue
